### ISSUE TITLE
Documentation of test functions

### ISSUE THREAD

**Issue by imanuelcostigan** [rstats-db/DBItest#108]
The test functions don't describe in detail the DBI specifications that are tested. I thought this was available in v1.3. Has this been deprecated in v1.4?

**Comment by krlmlr** [comment]
Thanks. Could you please be a bit more specific? Which help page are you looking at, what content do you expect?

**Comment by imanuelcostigan** [comment]
This is what I see with `DBItest::test_driver()` (v1.4):
![screen shot 2016-12-19 at 7 34 50 pm](https://cloud.githubusercontent.com/assets/2107580/21305921/58f5b1e8-c622-11e6-95fc-28116fc8d4ff.png)

Without digging into the source code, I don't actually know what I should expect will be tested and what success looks like for these test cases. I thought this was available previously?

**Comment by krlmlr** [comment]
I'm working on a comprehensive description that will cover all test functions, it's availabie at `?DBIspec`. Do you prefer if the tested specs also show up with the function's documentation?

**Comment by imanuelcostigan** [comment]
No that's fine - as long as I know where they are. My personal preference would be for each set of tests to be described in itemised fashion where the start of an item reflects the name of the testing function - would make it easier to trace back to source when something unexpected happens.

I take your comment to mean that there is more to be documented - for e.g., I don't see much on `test_result`. 

Thanks for your work on this. It is already really helpful and will be in longer run.

**Comment by imanuelcostigan** [comment]
I'm jotting down gaps as I see them so forgive me for the atomised comments. Another gap: test expectations with respect to how `dbBind()` should behave. For example, `spec_meta_bind` seems to have specific expectations on what dbBind should return and whether or not it should be visible but this is not available in either`?DBIspec` nor `?DBI::dbBind`

**Comment by krlmlr** [comment]
The way the specs are currently structured, everything that is part of the DBI spec is also part of a `spec_` topic in this package. This allows to find passages from the [ensemble spec](https://cran.r-project.org/web/packages/DBI/vignettes/spec.html) in this package if necessary, without having to look at the code. Closing this issue in favor of #128, which will ensure that these topics can be navigated.
