### ISSUE TITLE
column_info test inconsistent with spec

### ISSUE THREAD

**Issue by imanuelcostigan** [rstats-db/DBItest#109]
DBI::dbColumnInfo help:

> Value: A data.frame with one row per output field in res. **Methods MUST include name, field.type (the SQL type), and data.type (the R data type) columns, and MAY contain other database specific information like scale and precision or whether the field can store NULLs.**

This means the number of columns of the resulting col info data frame does not have to be two, whereas, in DBItest: 

```R
 ci <- dbColumnInfo(res)
expect_identical(colnames(ci), c("name", "type"))
```

And also, the name of the type field is assumed to be `type` rather than `field.type` per doc:

```R
 expect_is(ci$type, "character")
```

Let me know if I have interpreted this correctly and if you would like me to either submit a PR:

1. To change the DBI spec
2. Correct the DBItest cases

**Comment by krlmlr** [comment]
Thanks. I'll be fixing dbColumnInfo() specs soon, will take care of it. Would you like to comment on https://github.com/rstats-db/DBI/issues/75?

**Comment by krlmlr** [comment]
Closing in favor of rstats-db/DBI#75.
