### ISSUE TITLE
Support returning a hms object for time types

### ISSUE THREAD

**Issue by jimhester** [rstats-db/DBItest#134]
Currently `DBItest:::spec_sql_write_table$roundtrip_time()` throws an test error if you return a `c("hms", "difftime")` object from the database when the input is a simple difftime.

Specifically the error is from `expect_equal_df()`.
```
Attributes: < Component “class”: Lengths (2, 1) differ (string compare on first 1) >
Attributes: < Component “class”: 1 string mismatch >
target is hms, current is difftime
```

I could return just a `difftime` object, but would prefer to always return hms objects.

**Comment by krlmlr** [comment]
This is clearly wrong. Happy to review a PR.
