### ISSUE TITLE
Easy way to run a single test

### ISSUE THREAD

**Issue by hadley** [rstats-db/DBItest#136]
When you're debugging a test failure, it would be really nice if there was some simple way to run just one test, e.g.

```R
DBItest::test_only("^temporary_table$")
```

**Comment by krlmlr** [comment]
I tend to use negative lookahead for this. It's not the best solution, but works already:

```r
DBItest::test_all("(?!temporary_table).*")
```

I'll take a stab at a nicer solution in #129.

**Comment by krlmlr** [comment]
New `test_some()` available in master.
