### ISSUE TITLE
test_result: trivial_query - Why expect error from ClearResult after dbSendQuery(...,"select 1")?

### ISSUE THREAD

**Issue by marcelboldt** [rstats-db/DBItest#46]
`34:        on.exit(expect_error(dbClearResult(res), NA), add = TRUE)`

I guess it should be 

`on.exit(expect_true(dbClearResult(res), NA), add = TRUE)`

**Comment by krlmlr** [comment]
expect_error(..., NA) tests for "no error". It's just a posh way of writing try(...) in this context.

I remember issues when an on.exit() handler raised errors, perhaps they were propagated.

**Comment by marcelboldt** [comment]
Not sure if I get what you mean, however it works for me with expect_true. It's changed in my recent pull request (commit d492e00). Pls take an eye on that and change back if wrong...

**Comment by marcelboldt** [comment]
Sorry, my mistake. Found the error in my driver code. expect_error() is fine here.

**Comment by krlmlr** [comment]
Now using try_silent(), no need to generate an expectation.
