### ISSUE TITLE
Prefer warnings to errors for dbDisconnect() and dbClearResult()

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBItest#50]
if already disconnected/closed.

**Comment by hadley** [comment]
It would be useful to write up why (i.e. the underlying philosophy) somewhere, to make sure that we're consistent across functions (and so backend developers can understand the motivation for the design decisions)

**Comment by krlmlr** [comment]
I'm planning to do this for every aspect tested by DBItest.

For this particular case: Double disconnects/clears may be indicative of a programming error but should not abort a running analysis.

**Comment by krlmlr** [comment]
Done in v1.0.4.
