### ISSUE TITLE
Test backends as part of Travis-CI tests

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBItest#52]
in parallel, triggered by environment variable

**Comment by krlmlr** [comment]
@hannesmuehleisen: How do I test stable/bleeding-edge versions of MonetDB.R and MonetDBLite in Travis?

@marcelboldt: I see in https://github.com/EXASOL/r-exasol that you are already testing on Travis. Are you aware of the recent RODBCDBI package by @teramonagi?

**Comment by hannesmuehleisen** [comment]
@krlmlr  Travis?

**Comment by krlmlr** [comment]
@hannesmuehleisen: Basically, I'm looking for an unanttended install of the database engine on an Ubuntu 12.04 (14.04) box with root access, and for a script to download sources for the bleeding-edge version of MonetDB.R and MonetDBLite.

**Comment by hannesmuehleisen** [comment]
Ok, bleeding install for MonetDB.R/MonetDBLite: 

    install.packages(c("MonetDB.R", "MonetDBLite"), repos=c("http://dev.monetdb.org/Assets/R/", "http://cran.rstudio.com/"))

For MonetDB on Ubuntu, we have packages, see https://www.monetdb.org/downloads/deb/

**Comment by hadley** [comment]
It feels like testing should be job of the individual backends. I think the way we encourage the use of the tests is through a DBI-backend scorecard website or similar.

**Comment by hadley** [comment]
Ok - this is for testing DBItest, not for testing the backends.
