### ISSUE TITLE
Test that methods don't have special handling for row names by default

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBItest#54]
Automatic conversion of "row_names" column to row names.

- [x] dbFetch()
- [x] dbGetQuery()
- [ ] dbListFields()

**Comment by krlmlr** [comment]
Only for `dbReadTable()`; the other methods should avoid touching row names by default.

Existing backends will need to make the default behavior configurable via pkgconfig.

**Comment by krlmlr** [comment]
@hadley @gaborcsardi: I'd like to specify `dbGetQuery()` to not convert a `row_names` column to row names by default -- only `dbReadTable()` and `dbWriteTable()` should do this. Do you anticipate any problems here (except backward compatibility for existing backends, which can be handled with `pkgconfig`)?

**Comment by hadley** [comment]
Why do you want the behaviour to be different between these functions?

**Comment by gaborcsardi** [comment]
@hadley seconded. Unless it is causing trouble, I would not change it.

**Comment by krlmlr** [comment]
They operate at different conceptual levels.

`dbReadTable()` and `dbWriteTable()` attempt to serialize and deserialize a data frame. It's okay to support row names there, but we may as well draw the line here and not support them at all, at least not by default. (Again, pkgconfig.)

`dbGetQuery()` is about getting data from arbitrary queries back to R. Attaching special semantics to a column of a particular name is difficult to justify IMO, and calls for trouble. Just two examples:

- Some implementations of `dbListFields()` omit the `row_names` column
- `dplyr` doesn't roundtrip it: `memdb_frame(row_names = 1:3)`

I'd prefer to get rid of the default row names conversion for `dbGetQuery()`, and possibly also for `dbReadTable()` and `dbWriteTable()`.

**Comment by hadley** [comment]
Didn't we try and get rid of it for `dbReadTable()` in the past and it caused a lot of problems?  In an ideal world, there never would have been special handling for row names, but given how established DBI is, I think it's going to be hard to change now.

**Comment by krlmlr** [comment]
`row.names = FALSE` is now the default for `RSQLite`, with a pkgconfig switch. Let's see how this plays out.
