### ISSUE TITLE
test_sql creates invalid SQL

### ISSUE THREAD

**Issue by hannesmuehleisen** [rstats-db/DBItest#57]
There are lots of spaces missing in the created query: 

    SELECT'simple'as simple,'with spaces'as with_spaces,NULL as null_return,'NA'as na_return,

Perhaps `paste` should be used instead of `paste0` there: https://github.com/rstats-db/DBItest/blob/master/R/test_sql.R#L34

**Comment by krlmlr** [comment]
Are you sure this is invalid SQL?

```
sqlite> select'a';
a

mysql> select'a';
+---+
| a |
+---+
| a |
+---+
1 row in set (0.00 sec)

krlmlr=# select'a';
 ?column? 
----------
 a
(1 row)
```

I remember using paste0() on purpose here: This actually shows that the quotes have an effect, of course only if the SQL engine supports this and doesn't require whitespace. Would you like to add a tweak to DBItest?
