### ISSUE TITLE
dbWriteTable signature check too strict

### ISSUE THREAD

**Issue by hannesmuehleisen** [rstats-db/DBItest#58]
The signature check currently complains if the value argument to dbWriteTable is not fixed as a data frame. However, multiple things should be supported here, for example:
- simple vectors
- tbl_df objects from dplyr
- strings that point to filenames (supported by RSQLite and MonetDBLite)

**Comment by krlmlr** [comment]
Which test (name) are you referring to?

**Comment by hannesmuehleisen** [comment]
I think its that line: https://github.com/rstats-db/DBItest/blob/master/R/test_compliance.R#L87

**Comment by krlmlr** [comment]
The check only checks that there is a dbWriteTable function with signature "Connection, character, data.frame". You're free to support other signatures, too (case 1+3); each tbl_df should be a data.frame, and dispatch should just work here (case 2).

What should happen with single vectors?

We discussed standardization of "fast import" in https://github.com/rstats-db/DBI/issues/62 -- I think the conclusion was that there is no standard, and in many cases the file needs to be accessible by the server.

**Comment by krlmlr** [comment]
Closing, please open a new issue if this is still important.
