### ISSUE TITLE
dbDataType tests based on dispatch on driver

### ISSUE THREAD

**Issue by imanuelcostigan** [rstats-db/DBItest#69]
The `dbDataType` tests are included in the `test_driver` set rather than in the `test_connection` set. I can see how this works for RMySQL and RSQLite. However:

1. The `DBI` vignette seems to suggest to define this method for a Connection. This doesn't preclude the Connection method simply wrapping the Driver method - as is the case for RMySQL and RSQLite.
2. It makes this difficult for some DBI backends where the connection definitively establishes what SQL types are available. For example, the `DATE` T-SQL type is not available in versions of SQL Server earlier than SQL Server 2008.  The driver doesn't know about this, but the connection does (because you can determine the version number associated with SQL Server.

It is possible to skip the `test_driver` tests and it might be the case that for most SQL backends, the Driver does specify what SQL backend types are available. However, I am wondering if putting these in the Driver section of the test harness is the natural home for this.

**Comment by krlmlr** [comment]
This is an omission, dbDataType() should also be tested for a connection. (Drivers are free to skip the driver-based tests if the connection is necessary, or perhaps we add a tweak that governs this.) Happy to review a PR.

Note that dbDataType() should return an SQL object (#85), but this isn't tested yet.
