### ISSUE TITLE
Test multi-row binding

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/DBItest#96]
Aims:
- Good performance for multi-row binding if supported by the driver
- Seamless fallback support possible if the driver doesn't support binding
- **No new methods, so that it works with DBI 0.5**

Means:
- [x] `dbBind()` accepts multi-row input
- Query via `dbSendQuery()`
  - Need to call `dbFetch()`
  - `dbFetch()` always returns a data frame
  - Optional group ID in first column
    - [ ] `group.column` argument: name, `NULL` or `logical(1)`, default: `NULL`
  - How to fetch a single group, and then advance to the next?
    - [ ] `all.groups` argument: logical, default `TRUE`
  - How to return row counts for each parameter set?
    - [ ] `all.groups` argument to `dbGetRowCount()`: logical, default `TRUE`
- [x] Statement via `dbSendStatement()`
  - [ ] Executed immediately upon `dbBind()`
  - [x] `dbFetch()` is a no-op, returns NULL (for the fallback)
  - [ ] Rows affected are accumulated
  - [ ] `dbGetRowsAffected()` returns single value
  - How to return rows affected for each parameter set?
    - [ ] `all.groups` argument to `dbGetRowsAffected()`: logical, default `TRUE`
- [ ] Shortcuts via `params` argument to `dbSendQuery()` and `dbSendStatement()`

**Comment by gaborcsardi** [comment]
It would be amazing to make this work!

**Comment by krlmlr** [comment]
Thanks. Stay tuned, the overdue SQLite release will have most of that.

**Comment by krlmlr** [comment]
The open issues seem a bit ambitious and perhaps unnecessary. 

Multi-row binding for queries won't be supported at the moment until a real use case arises (#123).

Multi-row binding for statements is mostly used for inserting values into a table (at least for RSQLite). There seems to be no real need to retrieve the number of rows affected for each sub-statement.

**Comment by gaborcsardi** [comment]
I agree it is difficult. My main use case was `UPDATE`, actually. E.g. bind on a `PRIMARY KEY` column, and update the rest of the columns.

**Comment by krlmlr** [comment]
Oh, this should work already.

**Comment by gaborcsardi** [comment]
Oh, really? That's great! Can you point me to an example if there is one?

**Comment by krlmlr** [comment]
[`?RSQLite::dbBind`](http://rstats-db.github.io/RSQLite/reference/sqlite-query.html), but I'll also improve the DBI docs.

**Comment by gaborcsardi** [comment]
Cool, thanks!
